# Generated by Django 3.2.3 on 2021-05-14 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maaliuser',
            name='is_admin',
        ),
    ]
