# Generated by Django 3.2.3 on 2021-05-26 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_maaliuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='maaliuser',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
